mysite/mysite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("user.urls", namespace='user')),
	url(r"^shopcar/", include("shopcar.urls", namespace="shopcar")),
	url(r"^stores/", include("stores.urls", namespace="stores")),
	url(r"^goods/", include("goods.urls", namespace="goods")),
	url(r"^search/", include("haystack.urls")),
	url(r"^orders/", include("orders.urls", namespace="orders")),
	url(r"^", include("common.urls", namespace="common"))
]

mysite/orders/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r"^confirm/$", views.confirm, name="confirm"),
	url(r"^pay/$", views.pay, name="pay"),
	url(r"^done/$", views.done, name="done"),
	url(r"^list/$", views.list, name="list"),
	url(r"^(?P<o_id>\d+)/detail/$", views.detail, name="detail"),
]

mysite/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^login/$", views.user_login, name="login"),
    url(r"^register/$", views.register, name="register"),
    url(r"^user_logout/$", views.user_logout, name="user_logout"),
    url(r"^user_info/$", views.user_info, name="user_info"),
    url(r"^update/$", views.update, name="update"),
    url(r"^code/$", views.code, name="code"),
    url(r"^update_pw/$", views.update_pw, name="update_pw"),



]

mysite/goods/models.py
from django.db import models

# 导入店铺
from stores.models import Stores


# 商品类型模块
class GoodsType(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品类型名称
	name = models.CharField(max_length=255, unique=True, verbose_name="商品类名称")
	# 商品类型图片
	cover = models.ImageField(upload_to="static/goods", default="static/goods/1.jpg", verbose_name="商品类图片")
	# 商品类型描述
	intro= models.TextField(verbose_name="商品类描述")
	# 商品类型关联
	goodType = models.ForeignKey("self", null=True, blank=True, verbose_name="父级类型", on_delete=models.CASCADE)


# 商品类型
class Goods(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品名称
	name = models.CharField(max_length=255, verbose_name="商品名称")
	# 商品价格
	price = models.FloatField(verbose_name="商品单价")
	# 剩余库存
	stock = models.IntegerField(verbose_name="剩余库存")
	# 销量
	count = models.IntegerField(default=0, verbose_name="销量")
	# 上架时间
	creatTime = models.DateTimeField(auto_now_add=True)
	# 商品描述
	intro = models.TextField(verbose_name="商品描述")
	# 所属店铺
	store = models.ForeignKey(Stores, on_delete=models.CASCADE, verbose_name="商品所属店铺")
	# 所属类型
	goodsType = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name="商品所属类型")


# 商品图片的模块
class GoodsImage(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品图片存放路径
	path = models.ImageField(upload_to="static/goods", default="static/goods/2.jpg", verbose_name="商品图片")
	# 图片描述
	intro = models.TextField(null=True, blank=True, verbose_name="商品图片描述")
	# 默认显示的图片
	status = models.BooleanField(default=False, verbose_name="默认显示的图片")
	# 所属商品
	goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name="所属商品")

mysite/orders/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
	id = models.AutoField(primary_key=True)
	# 订单所属用户
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="所属用户")
	# 订单生成时间
	create_time = models.DateTimeField(auto_now_add=True, verbose_name="订单生成时间")
	# 收件人
	recv_name = models.CharField(max_length=100, verbose_name="收件人")
	# 收件人联系方式
	recv_tel = models.CharField(max_length=50, verbose_name="收件人电话")
	# 售货地址
	recv_address = models.CharField(max_length=255, verbose_name="收货地址")
	# 订单总金额
	all_price = models.FloatField(verbose_name="订单总金额")
	# 订单备注
	remake = models.CharField(max_length=255, verbose_name="备注信息")


class OrderItem(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品编号
	goods_id = models.IntegerField(verbose_name="商品编号")
	# 商品图片
	goods_img = models.CharField(max_length=255, verbose_name="商品图片")
	# 商品名称
	goods_name = models.CharField(max_length=255, verbose_name="商品名称")
	# 商品价格
	goods_price = models.FloatField(verbose_name="商品价格")
	# 购买数量
	goods_count = models.IntegerField(verbose_name="商品数量")
	# 商品总价
	goods_price_all = models.FloatField(verbose_name="成交价格")
	# 所属订单
	order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="所属订单")

mysite/orders/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.http import require_POST

from shopcar.models import ShopCart
from goods.models import Goods
from . import models
# from user.models import Address

@require_POST
def confirm(request):
	g_ids = request.POST.getlist("g_id")
	shop_carts = ShopCart.objects.filter(pk__in=g_ids)
	# addresses = Address.objects.filter(user=request.user)
	return render(request, "oeders/confirm.html", {"shop_carts":shop_carts})#, "addresses":addresses})


def pay(reuqest):
	pass


@require_POST
def done(request):
	c_ids = request.POST.getlist("c_id")
	address_id = request.POST["address"]

	address = Address.objects.get(pk=address_id)
	shopcarts = ShopCart.objects.filter(pk__in=c_ids)

	_address = address.recv_name + "|" + address.recv_tel + "|" + address.province + "|" + \
			   address.city + "|" + address.area + "|" + address.street + "|" + address.desc

	# 生成订单
	order = models.Order(address=address, user=request.user, recv_name=address.recv_name, recv_tel=address.recv_tel, \
						  all_price=0, remake="")

	order.save()
	allCount = 0
	for s in shopcarts:
		g = s.goods
		orderItem = models.OrderItem(goods_id=g.id, goods_img=g.goodsimage_set.all.firet.path,\
						goods_name=g.anme, goods_price=g.price, goods_count=s.count, \
						 goods_price_all=s.allTital)

		orderItem.save()
		allCount += s.allTotal
	order.all_price = allCount
	order.save()

	return redirect(reverse("orders:list"))


def list(request):
	orders = models.Order.objects.filter(user=request.user)
	return render(request, "orders/list.html", {"orders":orders})


def detail(request, o_id):
	pass

mysite/orders/templates/orders/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>确认订单</title>
</head>
<body>
    <h1>请确认需要提交的订单</h1>
    <form action="{% url 'orders:done' %}" method="post">
        {% csrf_token %}
        <table>
            {% for sc in shop_carts %}
            <input type="hidden" name="c_id" value="{{sc.id}}">
                <tr>
                    <td><img src="/{{sc.goods.goodsimage_set.all.first.path}}" alt="商品图片"></td>
                    <td>商品名称：{{sc.goods.name}}</td>
                    <td>商品数量：{{sc.count}}</td>
                    <td>小计金额：{{sc.allTotal}}</td>
                    <td></td>
                </tr>
            {% endfor %}
            <tr>
                <td>
                    {% for address in addresses %}
                        收货人：{{address.recv_name}} <br>
                        收货人电话：{{address.recv_tel}} <br>
                    {% if address.is_default %}
                        <input type="radio" name="address" checked value="{{address.id}}">
                    {% else %}
                        <input type="radio" name="address" value="{{address.id}}">
                </td>
            </tr>
        </table>
        <button>立即付款</button>
    </form>
</body>
</html>

mysite/orders/templates/orders/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单详情</title>
</head>
<body>

</body>
</html>

mysite/orders/templates/orders/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查看所有订单</title>
</head>
<body>
    <h1>你的所有订单</h1>
    {% for o in orders %}
        {{o.recv_name}}<br>
        {{o.recv_tel}}<br>
        {{o.recv_address}}<br>
        {{o.all_price }}<br>
        {{o.remake}}<br>
        <hr>
    {% endfor %}
</body>
</html>