mysite/mysite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("user.urls", namespace='user')),
	url(r"^shopcar/", include("shopcar.urls", namespace="shopcar")),
	url(r"^stores/", include("stores.urls", namespace="stores")),
	url(r"^goods/", include("goods.urls", namespace="goods")),
	url(r"^search/", include("haystack.urls")),
	url(r"^orders/", include("orders.urls", namespace="orders")),
	url(r"^", include("common.urls", namespace="common"))
]

mysite/stores/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	# 增加店铺
	url(r"^add/$", views.add, name="add"),
	# 查询店铺
	url(r"^list/$", views.list, name="list"),
	# 修改店铺
	url(r"^(?P<s_id>\d+)/update/$", views.update, name="update"),
	# 店铺详情
	url(r"^(?P<s_id>\d+)/detail/$", views.detail, name="detail"),
	# 关闭店铺
	url(r"^(?P<s_id>\d+)/(?P<status>\d+)/change/$", views.change, name="change"),
]

mysite/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^login/$", views.user_login, name="login"),
    url(r"^register/$", views.register, name="register"),
    url(r"^user_logout/$", views.user_logout, name="user_logout"),
    url(r"^user_info/$", views.user_info, name="user_info"),
    url(r"^update/$", views.update, name="update"),
    url(r"^code/$", views.code, name="code"),
    url(r"^update_pw/$", views.update_pw, name="update_pw"),



]

mysite/goods/models.py
from django.db import models

# 导入店铺
from stores.models import Stores


# 商品类型模块
class GoodsType(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品类型名称
	name = models.CharField(max_length=255, unique=True, verbose_name="商品类名称")
	# 商品类型图片
	cover = models.ImageField(upload_to="static/goods", default="static/goods/1.jpg", verbose_name="商品类图片")
	# 商品类型描述
	intro= models.TextField(verbose_name="商品类描述")
	# 商品类型关联
	goodType = models.ForeignKey("self", null=True, blank=True, verbose_name="父级类型", on_delete=models.CASCADE)


# 商品类型
class Goods(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品名称
	name = models.CharField(max_length=255, verbose_name="商品名称")
	# 商品价格
	price = models.FloatField(verbose_name="商品单价")
	# 剩余库存
	stock = models.IntegerField(verbose_name="剩余库存")
	# 销量
	count = models.IntegerField(default=0, verbose_name="销量")
	# 上架时间
	creatTime = models.DateTimeField(auto_now_add=True)
	# 商品描述
	intro = models.TextField(verbose_name="商品描述")
	# 所属店铺
	store = models.ForeignKey(Stores, on_delete=models.CASCADE, verbose_name="商品所属店铺")
	# 所属类型
	goodsType = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name="商品所属类型")


# 商品图片的模块
class GoodsImage(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品图片存放路径
	path = models.ImageField(upload_to="static/goods", default="static/goods/2.jpg", verbose_name="商品图片")
	# 图片描述
	intro = models.TextField(null=True, blank=True, verbose_name="商品图片描述")
	# 默认显示的图片
	status = models.BooleanField(default=False, verbose_name="默认显示的图片")
	# 所属商品
	goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name="所属商品")

mysite/stores/models.py
from django.db import models

from django.contrib.auth.models import User


class Stores(models.Model):
	id = models.AutoField(primary_key=True)
	# 店铺名称
	name = models.CharField(max_length=255, unique=True, verbose_name="店铺名称")
	# 店铺封面
	cover = models.ImageField(upload_to="static/stores", default="static/stores/3.jpg", verbose_name="店铺封面")
	# 店铺描述
	intro = models.TextField(verbose_name="店铺描述")
	# 开店时间
	openTime = models.DateTimeField(auto_now_add=True, verbose_name="开店时间")
	#店铺状态
	status = models.IntegerField(default=0, verbose_name="店铺状态")
	#店主
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="店主")

mysite/stores/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET

from . import models
from goods.models import GoodsType, Goods


# 增加店铺
@login_required()
def add(request):
	if request.method == "GET":
		return render(request, "stores/add.html", {})
	else:
		name = request.POST["name"].strip()
		intro = request.POST["intro"].strip()

		try:
			cover = request.FILES["cover"]
			store = models.Stores(name=name, intro=intro, cover=cover, user=request.user)
		except:
			store = models.Stores(name=name, intro=intro, user=request.user)
		store.save()

		return redirect(reverse("stores:detail", kwargs={"s_id": store.id}))


# 查询店铺
@require_GET
@login_required()
def list(request):
	stores = models.Stores.objects.filter(user=request.user, status__in=[0, 1])
	return render(request, "stores/list.html", {"stores": stores})


# 修改店铺
@login_required()
def update(request, s_id):
	if request.method == "GET":
		store = models.Stores.objects.get(pk=s_id)
		return render(request, "stores/update.html", {"store":store})
	else:
		name = request.POST["name"].strip()
		intro = request.POST["intro"].strip()

		store = models.Stores.objects.get(pk=s_id)
		store.name = name
		store.intro = intro
		try:
			cover = request.FILES["cover"]
			store.cover = cover
		except:
			pass
		store.save()

		return redirect(reverse("stores:detail", kwargs={"s_id": store.id}))


# 店铺详情
@login_required()
def detail(request, s_id):
	store = models.Stores.objects.get(pk=s_id)
	type1 = GoodsType.objects.filter(goodType__isnull=True)
	goods = Goods.objects.filter(store=store)
	return render(request, "stores/detail.html", {"store": store, "type1": type1, "goods": goods})


# 关闭店铺
@require_GET
@login_required()
def change(request, s_id, status):
	store = models.Stores.objects.get(pk=s_id)
	store.status = int(status)
	store.save()
	if store == 2:
		return redirect(reverse("stores:list"))
	else:
		return render(request, "stores/detail.html", {"store": store})

mysite/stores/templates/stores/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	{% load static %}
		<!--<script src="{% static 'js/lib/jquery2.2.4/jquery-2.2.4.js' %}"></script>-->
		<!--<script src="{% static '/js/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>-->
    <link rel="stylesheet" href="/static/stores/css/style.css">
    <link rel="stylesheet" href="/static/stores/css/hao.css">
</head>
<body>
<!-- start header -->
	<!-- 加载静态资源 -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="">购物车</a></div>
					<div class="fr">
						<ul>
                            {% if request.user.is_active %}
								<li><a href="{% url 'user:user_info' %}" target="_blank">欢迎{{user}}登录系统</a></li>
								<li>|</li>
								<li><a href="{% url 'user:user_logout'%}" target="_blank" >退出</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
                                <li><a href="/stores/list/">我的店铺</a></li>
							{% else %}
								<li><a href="{% url 'user:login'%}" target="_blank" >登录</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
							{% endif %}
							<!--<li><a href="/user/login/" target="_blank">登录</a></li>-->
							<!--<li>|</li>-->
							<!--<li><a href="/user/register/" target="_blank" >注册</a></li>-->
							<!--<li>|</li>-->
							<!--<li><a href="/stores/list/">我的店铺</a></li>-->
						</ul>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->

<!-- start banner_x -->
		<div class="banner_x center">
			<a href="/" target="_blank">
                <div class="logo fl" style="margin-top:25px">
                    <img src="/static/goods/logo_top.png" alt="">
                </div>
            </a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="./liebiao.html" target="_blank">小米手机</a></li>
					<li><a href="">红米</a></li>
					<li><a href="">平板·笔记本</a></li>
					<li><a href="">电视</a></li>
					<li><a href="">盒子·影音</a></li>
					<li><a href="">路由器</a></li>
					<li><a href="">智能硬件</a></li>
					<li><a href="">服务</a></li>
					<li><a href="">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>

		<h1 class="nbq">开业大吉</h1>
		<form action="{% url 'stores:add' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="nbw">店铺名称：<input type="text" name="name" class="nbw1" autocomplete="off"> <br></div>
		<div class="nbw">店铺封面：<input type="file" name="cover" id="cover" > <br></div>
		<div class="nbw">店铺介绍: </div>
		<div><textarea name="intro" id="intro" cols="30" rows="10" class="nbe"></textarea> <br></div>
		<input type="submit" value="开业大吉" class="nbr">
		</form>



</body>
</html>

mysite/stores/templates/stores/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>店铺详情页面</title>
    {% load static %}
    <script src="{% static 'js/lib/jquery2.2.4/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static '/js/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <!--<script src="/static/js/lib/jquery2.2.4/jquery-2.2.4.min.js}"></script>-->

    <link rel="stylesheet" href="/static/stores/css/detail.css">
    <!--<link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">-->
    <link rel="stylesheet" href="/static/stores/css/style.css">

</head>
<body>

	<!-- start header -->
	<!-- 加载静态资源 -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="">购物车</a></div>
					<div class="fr">
						<ul>
							{% if request.user.is_active %}
								<li><a href="{% url 'user:user_info' %}" target="_blank">欢迎{{user}}登录系统</a></li>
								<li>|</li>
								<li><a href="{% url 'user:user_logout'%}" target="_blank" >退出</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
                                <li><a href="/stores/list/">我的店铺</a></li>
							{% else %}
								<li><a href="{% url 'user:login'%}" target="_blank" >登录</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
							{% endif %}
						</ul>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->

<!-- start banner_x -->
		<div class="banner_x center">
			<a href="/" target="_blank">
                <div class="logo fl" style="margin-top:25px">
                    <img src="/static/goods/logo_top.png" alt="">
                </div>
            </a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="./liebiao.html" target="_blank">小米手机</a></li>
					<li><a href="">红米</a></li>
					<li><a href="">平板·笔记本</a></li>
					<li><a href="">电视</a></li>
					<li><a href="">盒子·影音</a></li>
					<li><a href="">路由器</a></li>
					<li><a href="">智能硬件</a></li>
					<li><a href="">服务</a></li>
					<li><a href="">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->

    <div class="stores">
    <!--<h1>店铺详情页面</h1>-->
        <div class="stores_left">
            <div class="stores_img"><img src="/static/upload/{{store.cover}}" alt="头像"></div>
        </div>

        <div class="stores_right">
            <div class="stores_name"><h1>{{store.name}}</h1></div><br>
            <div class="stores_intro">{{store.intro}}</div><br>
            <div class="stores_status">
                    {% if store.status == 0 %}
                        <p>正在营业</p>
                        <button><a href="{% url 'stores:change' store.id 1 %}">暂停营业</a></button>
                        <button><a href="{% url 'stores:change' store.id 2 %}">删除店铺</a></button>
                    {% elif store.status == 1 %}
                        <p>暂停营业</p>
                        <button><a href="{% url 'stores:change' store.id 0 %}">开始营业</a></button>
                        <button><a href="{% url 'stores:change' store.id 2 %}">删除店铺</a></button>
                    {% elif store.status == 2 %}
                        <p>店铺已经被删除，请联系管理员</p>
                    {% endif %}
            </div><br>
            <div class="stores_caozuo">
                    <button><a href="{% url 'stores:update' store.id %}">修改店铺信息</a></button>
                    <button><a href="{% url 'goods:add' store.id %}">上架商品</a></button>
                    <button><a href="{% url 'stores:add' %}">开店</a></button>
            </div>
        </div>
    </div>
    <div class="goods">
        <div class="biaoti center"><h2>店铺商品</h2></div>
        <div class="main center"><!--<div class="row">-->
            {% for g in goods %}
            <div class="good">
                <div class="sub_mingxing">
                    <a href="{% url 'goods:detail' g.id %}">
                        <img src="/static/upload/{{g.goodsimage_set.all.first.path}}" alt="商品图片">
                    </a>
                </div>
                <div class="pinpai"><a href="{% url 'goods:detail' g.id %}">{{g.name}}</a></div>
                <div class="youhui">{{g.intro | truncatechars:20}}</div>
                <div class="jiage">{{g.price}}元</div>
                <a class="xiangqing" href="{% url 'goods:detail' g.id %}">查看商品详情</a>
            </div>
            {% empty %}
                当前没有商品呢
            {% endfor %}
        </div>
    </div>


<script>
    $(function(){
        $("#type1").on("change",function(){
            $.ajax({
                url:"/goods/findType/",
                type:"get",
                data:{"goodType_id":$(this).val()},
                success:function(data){
                    $("#type2").empty()
                    data = JSON.parse(data);
                    for (var i = 0; i < data.length; i++){
                        var type = data[i];
                        $op = $("<option>");
                        $op.attr("value", type.pk)
                        $op.text(type.fields.name)
                        $("#type2").append($op)
                    }
                },
                error:function(){
                    alert("网络异常，请重新点击")
                }
            });
        });
    })
</script>

</body>
</html>

<!--<tr >-->
            <!--<td></td>-->
        <!--</tr>-->
        <!--<tr class="stores_name">-->
            <!--<td>店铺名称</td>-->
            <!--<td>{{store.name}}</td>-->
        <!--</tr>-->
        <!--<br>-->
        <!--<tr class="stores_intro">-->
            <!--<td>店铺介绍</td>-->
            <!--<td>{{store.intro}}</td>-->
        <!--</tr>-->
        <!--<tr class="stores_status">-->
            <!--<td>店铺状态</td>-->
            <!--<td>-->
                <!--{% if store.status == 0 %}-->
                    <!--<p>正在营业</p>-->
                    <!--<button><a href="{% url 'stores:change' store.id 1 %}">暂停营业</a></button>-->
                    <!--<button><a href="{% url 'stores:change' store.id 2 %}">删除店铺</a></button>-->
                <!--{% elif store.status == 1 %}-->
                    <!--<p>暂停营业</p>-->
                    <!--<button><a href="{% url 'stores:change' store.id 0 %}">开始营业</a></button>-->
                    <!--<button><a href="{% url 'stores:change' store.id 2 %}">删除店铺</a></button>-->
                <!--{% elif store.status == 2 %}-->
                    <!--<p>店铺已经被删除，请联系管理员</p>-->
                <!--{% endif %}-->
            <!--</td>-->
        <!--</tr>-->
        <!--<tr class="stores_caozuo">-->
            <!--<td>操作</td>-->
            <!--<td>-->
                <!--<button><a href="{% url 'stores:update' store.id %}">修改店铺信息</a></button>-->
                <!--<button><a href="{% url 'goods:add' store.id %}">上架商品</a></button>-->
            <!--</td>-->
        <!--</tr>-->


    <!--<hr>-->
    <!--<h1>上架商品</h1>-->
    <!--<form action="{% url 'goods:add' store.id %}" method="post" enctype="multipart/form-data">-->
        <!--{% csrf_token %}-->
        <!--商品名称：<input type="text" name="name" id="name"> <br>-->
        <!--商品单价：<input type="number" name="price"> <br>-->
        <!--商品库存：<input type="number" name="stock"> <br>-->
        <!--&lt;!&ndash;<input type="hidden" name="store" value="{{store.id}}"> <br>&ndash;&gt;-->
        <!--商品图片：<input type="file" name="cover"><button>继续添加</button> <br>-->
        <!--商品类型：-->
            <!--<select name="type1" id="type1">-->
                <!--<option value="-1">请选择一级类型</option>-->
                <!--{% for t in type1 %}-->
                <!--<option value="{{t.id}}">{{t.name}}</option>-->
                <!--{% endfor %}-->
            <!--</select>-->
            <!--<select name="type2" id="type2">-->
                <!--<option value=""></option>-->
            <!--</select> <br>-->
        <!--商品介绍：-->
        <!--<textarea name="intro" id="intro" cols="30" rows="10"></textarea> <br>-->
        <!--<button type="submit" class="btn btn-default submit-btn">添加商品</button>-->
    <!--</form>-->
    <!--<hr>-->


<!--<div class="danpin center">-->




				<!--<div class="mingxing fl">-->
					<!--<div class="sub_mingxing"><a href=""><img src="{% static 'common/img/pinpai2.png'%}" alt=""></a></div>-->
					<!--<div class="pinpai"><a href="">小米5s</a></div>-->
					<!--<div class="youhui">5月9日-10日，下单立减200元</div>-->
					<!--<div class="jiage">1999元</div>-->
				<!--</div>-->
				<!--<div class="mingxing fl">-->
					<!--<div class="sub_mingxing"><a href=""><img src="{% static 'common/img/pinpai3.png'%}" alt=""></a></div>-->
					<!--<div class="pinpai"><a href="">小米手机5 64GB</a></div>-->
					<!--<div class="youhui">5月9日-10日，下单立减100元</div>-->
					<!--<div class="jiage">1799元</div>-->
				<!--</div>-->
				<!--<div class="mingxing fl">-->
					<!--<div class="sub_mingxing"><a href=""><img src="{% static 'common/img/pinpai4.png' %}" alt=""></a></div>-->
					<!--<div class="pinpai"><a href="">小米电视5s 55英寸</a></div>-->
					<!--<div class="youhui">5月9日，下单立减200元</div>-->
					<!--<div class="jiage">3999元</div>-->
				<!--</div>-->
				<!--<div class="mingxing fl">-->
					<!--<div class="sub_mingxing"><a href=""><img src="{% static 'common/img/pinpai5.png' %}" alt=""></a></div>-->
					<!--<div class="pinpai"><a href="">小米笔记本</a></div>-->
					<!--<div class="youhui">更轻更薄，像杂志一样随身携带</div>-->
					<!--<div class="jiage">3599元起</div>-->
				<!--</div>-->
				<!--<div class="clear"></div>-->
			<!--</div>-->
		<!--</div>-->
    <!--<footer class="mt20 center">-->
        <!--<div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>-->
        <!--<div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div>-->
        <!--<div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>-->
    <!--</footer>-->

mysite/stores/templates/stores/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询自己所有的店铺</title>
    {% load static %}
    <script src="{% static 'js/lib/jquery2.2.4/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static '/js/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <!--<script src="/static/js/lib/jquery2.2.4/jquery-2.2.4.min.js}"></script>-->

    <link rel="stylesheet" href="/static/stores/css/list.css">
    <!--<link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">-->
    <link rel="stylesheet" href="/static/stores/css/style.css">
</head>
<body>
<!-- start header -->
	<!-- 加载静态资源 -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="">购物车</a></div>
					<div class="fr">
						<ul>
							{% if request.user.is_active %}
								<li><a href="{% url 'user:user_info' %}" target="_blank">欢迎{{user}}登录系统</a></li>
								<li>|</li>
								<li><a href="{% url 'user:user_logout'%}" target="_blank" >退出</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
                                <li><a href="/stores/list/">我的店铺</a></li>
							{% else %}
								<li><a href="{% url 'user:login'%}" target="_blank" >登录</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
							{% endif %}
						</ul>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->

<!-- start banner_x -->
		<div class="banner_x center">
			<a href="/" target="_blank">
                <div class="logo fl" style="margin-top:25px">
                    <img src="/static/goods/logo_top.png" alt="">
                </div>
            </a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="./liebiao.html" target="_blank">小米手机</a></li>
					<li><a href="">红米</a></li>
					<li><a href="">平板·笔记本</a></li>
					<li><a href="">电视</a></li>
					<li><a href="">盒子·影音</a></li>
					<li><a href="">路由器</a></li>
					<li><a href="">智能硬件</a></li>
					<li><a href="">服务</a></li>
					<li><a href="">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->
    <div class="stores">
        <h1 class="stores_title">您的店铺</h1>
        <hr>
        {% for store in stores %}
            <div class="stores_left">
                <div class="stores_img"><img src="/static/upload/{{store.cover}}" alt="头像"></div>
            </div>
            <div class="stores_right">
                <div class="stores_name"><h1>{{store.name}}</h1></div><br>
                <div class="stores_intro">{{store.intro}}</div><br>
                <div class="stores_caozuo">
                    <button><a href="{% url 'stores:detail' store.id %}">进入店铺</a></button>
                </div>
            </div>
        {% empty %}
            <h3><a href="{% url 'stores:add' %}">没有查询到您的店铺，快去开店吧</a></h3>
        {% endfor %}
        </div>
    </div>
</body>
</html>

mysite/stores/templates/stores/list1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查看自己的所有的店铺</title>
</head>
<body>
    <h1>查看自己的所有的店铺</h1>
    <table border="1">
        {% for store in stores %}
        <tr>
            <td>店铺头像</td>
            <td><img src="/{{store.cover}}" alt="店铺头像"></td>
        </tr>
        <tr>
            <td>店铺名称</td>
            <td>{{store.name}}</td>
        </tr>
        <tr>
            <td>店铺介绍</td>
            <td>{{store.intro}}</td>
        </tr>
        <tr>
            <td><a href="{% url 'stores:detail' store.id %}">查询详情</a></td>
        </tr>
        {% empty %}
        <tr>
            <td>没有查询到您的店铺，快去<a href="{% url 'stores:add' %}">开店</a>吧</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>