mysite/goods/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r"^(?P<store_id>\d+)/add/$", views.add, name="add"),
	url(r"^(?P<g_id>\d+)/detail/$", views.detail, name="detail"),
	url(r"^(?P<g_id>\d+)/update/$", views.update, name="update"),
	url(r"^(?P<g_id>\d+)/delete/$", views.delete, name="delete"),
	url(r"^findType/$", views.findType, name="findType"),
]

mysite/mysite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("user.urls", namespace='user')),
	url(r"^shopcar/", include("shopcar.urls", namespace="shopcar")),
	url(r"^stores/", include("stores.urls", namespace="stores")),
	url(r"^goods/", include("goods.urls", namespace="goods")),
	url(r"^search/", include("haystack.urls")),
	url(r"^orders/", include("orders.urls", namespace="orders")),
	url(r"^", include("common.urls", namespace="common"))
]

mysite/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^login/$", views.user_login, name="login"),
    url(r"^register/$", views.register, name="register"),
    url(r"^user_logout/$", views.user_logout, name="user_logout"),
    url(r"^user_info/$", views.user_info, name="user_info"),
    url(r"^update/$", views.update, name="update"),
    url(r"^code/$", views.code, name="code"),
    url(r"^update_pw/$", views.update_pw, name="update_pw"),



]

mysite/goods/models.py
from django.db import models

# 导入店铺
from stores.models import Stores


# 商品类型模块
class GoodsType(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品类型名称
	name = models.CharField(max_length=255, unique=True, verbose_name="商品类名称")
	# 商品类型图片
	cover = models.ImageField(upload_to="static/goods", default="static/goods/1.jpg", verbose_name="商品类图片")
	# 商品类型描述
	intro= models.TextField(verbose_name="商品类描述")
	# 商品类型关联
	goodType = models.ForeignKey("self", null=True, blank=True, verbose_name="父级类型", on_delete=models.CASCADE)


# 商品类型
class Goods(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品名称
	name = models.CharField(max_length=255, verbose_name="商品名称")
	# 商品价格
	price = models.FloatField(verbose_name="商品单价")
	# 剩余库存
	stock = models.IntegerField(verbose_name="剩余库存")
	# 销量
	count = models.IntegerField(default=0, verbose_name="销量")
	# 上架时间
	creatTime = models.DateTimeField(auto_now_add=True)
	# 商品描述
	intro = models.TextField(verbose_name="商品描述")
	# 所属店铺
	store = models.ForeignKey(Stores, on_delete=models.CASCADE, verbose_name="商品所属店铺")
	# 所属类型
	goodsType = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name="商品所属类型")


# 商品图片的模块
class GoodsImage(models.Model):
	id = models.AutoField(primary_key=True)
	# 商品图片存放路径
	path = models.ImageField(upload_to="static/goods", default="static/goods/2.jpg", verbose_name="商品图片")
	# 图片描述
	intro = models.TextField(null=True, blank=True, verbose_name="商品图片描述")
	# 默认显示的图片
	status = models.BooleanField(default=False, verbose_name="默认显示的图片")
	# 所属商品
	goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name="所属商品")

mysite/goods/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.http import require_GET  # 请求
from django.core.serializers import serialize  # 序列化
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required  # 登陆后才能使用，否则跳到登陆界面

from . import models
from stores.models import Stores
from goods.models import Goods


# 商品增加
@login_required
def add(request, store_id):
	if request.method == "GET":
		type1 = models.GoodsType.objects.filter(goodType__isnull=True)
		return render(request, "goods/add.html", {"store_id": store_id, "type1": type1})
	else:
		name = request.POST["name"]
		price = request.POST["price"]
		stock = request.POST["stock"]
		# store_id = request.POST["store"]
		type2 = request.POST["type2"]
		intro = request.POST["intro"]
		cover = request.FILES["cover"]

		store = Stores.objects.get(pk=store_id)
		goodsType = models.GoodsType.objects.get(pk=type2)

		# 数据验证

		goods = models.Goods(name=name, price=price, stock=stock, intro=intro, store=store, goodsType=goodsType)
		goods.save()

		goodImage = models.GoodsImage(path=cover, goods=goods)
		goodImage.save()

		return redirect(reverse("stores:detail", kwargs={"s_id": store.id}))


# 二级类型查询函数
@require_GET
def findType(request):
	goodType_id = request.GET["goodType_id"]
	type2 = models.GoodsType.objects.filter(goodType=goodType_id)
	return HttpResponse(serialize("json", type2))


# 商品详情界面
@login_required
def detail(request, g_id):
	goods = models.Goods.objects.get(pk=g_id)
	return render(request, "goods/detail.html", {"goods": goods})



# 修改商品
@login_required
def update(request, g_id):
	return redirect("/")
	# if request.method == "GET":
	# 	# type1 = models.GoodsType.objects.filter(goodType__isnull=True)
	# 	goods = models.Goods.objects.get(pk=g_id)
	# 	return render(request, "goods/update.html", {"goods": goods, "store": goods.store})
	# else:
	# 	name = request.POST.get("name")
	# 	price = request.POST["price"]
	# 	stock = request.POST["stock"]
	# 	store_id = request.POST["store"]
	# 	type2 = request.POST["type2"]
	# 	intro = request.POST["intro"]
	# 	cover = request.FILES["cover"]
	#
	# 	store = Stores.objects.get(pk=store_id)
	# 	# goodsType = models.GoodsType.objects.get(pk=type2)
	#
	# 	# 数据验证
	#
	# 	goods = models.Goods(name=name, price=price, stock=stock, intro=intro, store=store, goodsType=type2)
	# 	goods.save()
	#
	# 	goodImage = models.GoodsImage(path=cover, goods=goods)
	# 	goodImage.save()
	#
	# 	return redirect(reverse("stores:detail", kwargs={"g_id": g_id}))


# 删除商品
@login_required
def delete(request, g_id):
	return redirect("/")

mysite/goods/templates/goods/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上架商品</title>
    {% load static %}
    <script src="{% static 'js/lib/jquery2.2.4/jquery-2.2.4.min.js' %}"></script>
    <!--<script src="{% static '/js/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>-->
    <!--<script src="/static/js/lib/jquery2.2.4/jquery-2.2.4.min.js}"></script>-->
	<link rel="stylesheet" href="/static/goods/css/hao.css">
    <link rel="stylesheet" href="/static/stores/css/detail.css">
    <!--<link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">-->
    <link rel="stylesheet" href="/static/stores/css/style.css">
</head>
<body>
<!-- start header -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="">购物车</a></div>
					<div class="fr">
						<ul>
							{% if request.user.is_active %}
								<li><a href="{% url 'user:user_info' %}" target="_blank">欢迎{{user}}登录系统</a></li>
								<li>|</li>
								<li><a href="{% url 'user:user_logout'%}" target="_blank" >退出</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
                                <li><a href="/stores/list/">我的店铺</a></li>
							{% else %}
								<li><a href="{% url 'user:login'%}" target="_blank" >登录</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
							{% endif %}
						</ul>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->

<!-- start banner_x -->
		<div class="banner_x center">
			<a href="/" target="_blank">
                <div class="logo fl" style="margin-top:25px">
                    <img src="/static/goods/logo_top.png" alt="">
                </div>
            </a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="">小米手机</a></li>
					<li><a href="">红米</a></li>
					<li><a href="">平板·笔记本</a></li>
					<li><a href="">电视</a></li>
					<li><a href="">盒子·影音</a></li>
					<li><a href="">路由器</a></li>
					<li><a href="">智能硬件</a></li>
					<li><a href="">服务</a></li>
					<li><a href="">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru" style="fontsize:20px;"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->
    <h1 class="mi_top">上架商品</h1>
    <div>
        <form action="{% url 'goods:add' store_id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mi0">商品名称：<input type="text" name="name" id="name" class="xm1"> <br></div>
            <div class="mi0">商品单价：<input type="number" name="price" class="xm1"> <br></div>
            <div class="mi0">商品库存：<input type="number" name="stock" class="xm1"> <br></div>
            <!--<input type="hidden" name="store" value="{{store.id}}"> <br>-->
            <div class="mi0">商品图片：<input type="file" name="cover"><button>继续添加</button> <br></div>
            <div class="mi0">商品类型：
				<select name="type1" id="type1">
                    <option value="-1">请选择一级类型</option>
                    {% for t in type1 %}
                    <option value="{{t.id}}">{{t.name}}</option>
                    {% endfor %}
                </select>
                <select name="type2" id="type2">
                    <option value=""></option>
                </select> <br>
			</div>

			<div class="mi0">商品介绍：</div>
			<div class="mi1">
				<textarea name="intro" id="intro" cols="30" rows="10" class="mi1"></textarea> <br>
			</div>

            <button type="submit" class="btn btn-default submit-btn mi2" >添加商品</button>
        </form>
    </div>


<script>
    $(function(){
        $("#type1").on("change",function(){
            $.ajax({
                url:"/goods/findType/",
                type:"get",
                data:{"goodType_id":$(this).val()},
                success:function(data){
                    $("#type2").empty()
                    data = JSON.parse(data);
                    for (var i = 0; i < data.length; i++){
                        var type = data[i];
                        $op = $("<option>");
                        $op.attr("value", type.pk)
                        $op.text(type.fields.name)
                        $("#type2").append($op)
                    }
                },
                error:function(){
                    alert("网络异常，请重新点击")
                }
            });
        });
    })
</script>

</body>
</html>

mysite/goods/templates/goods/detail.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
	<head>
		{% load static %}
		<meta charset="UTF-8">
        <meta name="author" content="order by dede58.com"/>
		<title>小米商城--商品详情</title>
		<!--<link rel="stylesheet" type="text/css" href="./css/style.css">-->
		<link rel="stylesheet" type="text/css" href="/static/goods/css/style.css">
		<script src="{% static 'js/lib/jquery2.2.4/jquery-2.2.4.min.js' %}"></script>

	</head>
	<body>
	<!-- start header -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="">购物车</a></div>
					<div class="fr">
						<ul>
							{% if request.user.is_active %}
								<li><a href="{% url 'user:user_info' %}" target="_blank">欢迎{{user}}登录系统</a></li>
								<li>|</li>
								<li><a href="{% url 'user:user_logout'%}" target="_blank" >退出</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
                                <li><a href="/stores/list/">我的店铺</a></li>
							{% else %}
								<li><a href="{% url 'user:login'%}" target="_blank" >登录</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
							{% endif %}
						</ul>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->

<!-- start banner_x -->
		<div class="banner_x center">
			<a href="/" target="_blank">
                <div class="logo fl" style="margin-top:25px">
                    <img src="/static/goods/logo_top.png" alt="">
                </div>
            </a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="">小米手机</a></li>
					<li><a href="">红米</a></li>
					<li><a href="">平板·笔记本</a></li>
					<li><a href="">电视</a></li>
					<li><a href="">盒子·影音</a></li>
					<li><a href="">路由器</a></li>
					<li><a href="">智能硬件</a></li>
					<li><a href="">服务</a></li>
					<li><a href="">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru" style="fontsize:20px;"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->

	
	<!-- xiangqing -->
	<form action="" method="">
	<div class="xiangqing">
		<div class="neirong w">
			<div class="xiaomi6 fl">{{goods.name}}</div>
			<nav class="fr">
				<li><a href="">概述</a></li>
				<li>|</li>
				<li><a href="">变焦双摄</a></li>
				<li>|</li>
				<li><a href="">设计</a></li>
				<li>|</li>
				<li><a href="">参数</a></li>
				<li>|</li>
				<li><a href="">F码通道</a></li>
				<li>|</li>
				<li><a href="">用户评价</a></li>
				<div class="clear"></div>
			</nav>
			<div class="clear"></div>
		</div>	
	</div>
	
	<div class="jieshao mt20 w">
		<!--<div class="left fl"><img src="./image/liebiao_xiaomi6.jpg"></div>-->
		<!--<div class="left fl"><img style="width:560px; height:560px" src="/static/goods/9.jpg" alt="商品图片"></div>-->
		<div class="left fl"><img style="width:560px; height:560px" src="/static/upload/{{goods.goodsimage_set.all.first.path}}" alt="商品图片"></div>
		<!--<div class="left fl"><img style="width:560px; height:560px" src="/{{goods.cover}}" alt="商品图片"></div>-->
		<div class="right fr">
			<!--<div class="h3 ml20 mt20">小米6</div>-->
			<div class="h3 ml20 mt20">{{goods.name}}</div>
			<!--<div class="jianjie mr40 ml20 mt10">变焦双摄，4 轴防抖 / 骁龙835 旗舰处理器，6GB 大内存，最大可选128GB 闪存 / 5.15" 护眼屏 / 四曲面玻璃/陶瓷机身</div>-->
			<div class="jianjie mr40 ml20 mt10">{{goods.intro}}</div>
			<!--<div class="jiage ml20 mt10">2499.00元</div>-->
			<div class="jiage ml20 mt10">{{goods.price}}元</div>
			<div class="ft20 ml20 mt20">选择版本</div>
			<div class="xzbb ml20 mt10">
				<div class="banben fl">
					<a>
						<span>全网通版 6GB+64GB </span>
						<span>{{goods.price}}元</span>
					</a>
				</div>
				<div class="banben fr">
					<a>
						<span>全网通版 6GB+128GB</span>
						<span>2899元</span>
					</a>
				</div>
				<div class="clear"></div>
			</div>
			<div class="ft20 ml20 mt20">选择颜色</div>
			<div class="xzbb ml20 mt10">
				<div class="banben">
					<a>
						<span class="yuandian"></span>
						<span class="yanse">亮黑色</span>
					</a>
				</div>

			</div>
			<div class="xqxq mt20 ml20">
				<div class="top1 mt10">
					<!--<div class="left1 fl">小米6 全网通版 6GB内存 64GB 亮黑色</div>-->
					<div class="left1 fl">{{goods.name}}&nbsp;|&nbsp;{{goods.intro}}</div>
					<div class="right1 fr">{{goods.price}}元</div>
					<div class="clear"></div>
				</div>
				<!--<div class="bot mt20 ft20 ftbc">总计：2499元</div>-->
				<div class="bot mt20 ft20 ftbc">总计：{{goods.price}}元</div>
			</div>
			<div class="xiadan ml20 mt20">
					<input class="jrgwc"  type="button" name="jrgwc" value="立即选购" />
				    <input class="jrgwc addGoods" type="button" goods_id="{{goods.id}}" value="添加购物车">
			</div>
		</div>
		<!--<div class="clear"></div>-->
	</div>
	</form>
	<!-- footer -->
	<footer class="mt20 center">
			
			<div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
			<div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div> 
			<div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>

		</footer>
	<script>
		$(function () {
			$(".addGoods").on('click', function () {
				var _goods_id = $(this).attr("goods_id");
				$.ajax({
					url: "/shopcar/1/"+_goods_id+"/add/",
					type:"get",
					// dataType: "json",
					data: {"csrfmiddlewaretoken": "{{ csrf_token }}"},
					success: function (msg) {
					    // alert(msg.msg);
						alert("添加成功");
                    },
					error:function(data,type, err){
						console.log("ajax错误类型："+type);
	         			console.log(err);
	   				 }
				})
            })
        })

	</script>







	</body>
</html>

mysite/goods/templates/goods/detail1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商品详情界面</title>
</head>
<body>
    <h1>商品详情界面</h1>
    <div class="good-img">
        <img src="/user/static/upload/static/{{goods.goodsimage_set.all.filter.path}}" alt="商品图片">
        <!--<img src="/user/static/upload/static/goods/7_3C5fQKJ.jpg" alt="商品图片">-->
        <!--<img src="/.user/static/upload/static/goods/3_yyt3fWw.jpg" alt="商品图片">-->
        <!--<img src="/.user/static/upload/static/goods/3_yyt3fWw.jpg" alt="商品图片">-->
        <!--<img src="/static/img/login_bg.jpg" alt="商品图片">-->
        <!--<img src="/{{goods.goodsimage_set.all.first.path}}" alt="没有">-->


    </div>
    <div class="good-name">
        {{goods.name}}
    </div>
    <div class="good-intro">
        {{goods.intro}}
    </div>
    <div class="good-price">
        单价：{{goods.price}}|销量：{{goods.count}}
    </div>
    <div class="shopcar">
        <a href="#">加入购物车</a>
    </div>
</body>
</html>

mysite/goods/templates/goods/update.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>修改商品信息</title>-->
<!--</head>-->
<!--<body>-->
    <!--<h1>修改商品信息</h1>-->
    <!--<form action="{% url 'goods:update' goods.id %}" method="post" enctype="multipart/form-data">-->
        <!--{% csrf_token %}-->
        <!--商品名称：<input type="text" name="name" value="{{goods.name}}"> <br>-->
        <!--商品单价：<input type="number" name="price" value="{{goods.price}}"> <br>-->
        <!--商品库存：<input type="number" name="stock" value="{{goods.stock}}"> <br>-->
        <!--<input type="text" name="store" value="{{store.id}}"> <br>-->
        <!--商品图片：<img src="/{{goods.goodsimage_set.all.first.path}}" alt=""> <br>-->
        <!--&lt;!&ndash;商品图片：<input type="file" name="cover"><button>继续添加</button> <br>&ndash;&gt;-->
        <!--商品图片：<input type="file" name="cover"><br>-->
        <!--&lt;!&ndash;商品类型：&ndash;&gt;-->
        <!--&lt;!&ndash;商品类型： <input type="text" name="type2" value="{{goods.goodsType}}">&ndash;&gt;-->
            <!--<select name="type1" id="type1">-->
                <!--<option value="-1">请选择一级类型</option>-->
                <!--{#{% for t in type1 %}#}-->
                <!--<option value="{{t.id}}">{{t.name}}</option>-->
                <!--{#{% endfor %}#}-->
            <!--</select>-->
            <!--<select name="type2" id="type2">-->
                <!--<option value=""></option>-->
            <!--</select> <br>-->
        <!--商品介绍：-->
        <!--<textarea name="intro" id="intro" cols="30" rows="10" >{{goods.intro}}</textarea> <br>-->
        <!--<button type="submit" class="btn btn-default submit-btn">保存修改</button>-->
    <!--</form>-->
<!--</body>-->
<!--</html>-->