mysite/mysite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("user.urls", namespace='user')),
	url(r"^shopcar/", include("shopcar.urls", namespace="shopcar")),
	url(r"^stores/", include("stores.urls", namespace="stores")),
	url(r"^goods/", include("goods.urls", namespace="goods")),
	url(r"^search/", include("haystack.urls")),
	url(r"^orders/", include("orders.urls", namespace="orders")),
	url(r"^", include("common.urls", namespace="common"))
]

mysite/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^login/$", views.user_login, name="login"),
    url(r"^register/$", views.register, name="register"),
    url(r"^user_logout/$", views.user_logout, name="user_logout"),
    url(r"^user_info/$", views.user_info, name="user_info"),
    url(r"^update/$", views.update, name="update"),
    url(r"^code/$", views.code, name="code"),
    url(r"^update_pw/$", views.update_pw, name="update_pw"),



]

mysite/user/models.py
from django.db import models
# from datetime import datetime
# 引入django 中的用户表
from django.contrib.auth.models import User
# Create your models here.





class UserInfo(models.Model):
    # 编号
    id = models.AutoField(primary_key=True)
    # 用户昵称
    nickname = models.CharField(max_length=255, unique=True, verbose_name="用户昵称")
    # 用户年龄
    age = models.IntegerField(default=18, verbose_name="用户年龄")
    # 用户性别
    gender = models.CharField(max_length=10, default='男', verbose_name="用户性别")
    # 用户头像
    header = models.ImageField(upload_to="header/", default="header/enen.jpg", verbose_name="用户头像")
    # 联系电话
    phone = models.CharField(max_length=50, default='11111111111', verbose_name="联系方式")
    # 一对一关联用户表
    user = models.OneToOneField(User, on_delete=models.CASCADE)

mysite/user/views.py
from io import BytesIO

from django.http import HttpResponse


from django.shortcuts import render
# 引入数据库用户名表
from django.contrib.auth.models import User
# django内置的登陆推出方法
from django.contrib.auth import authenticate, logout, login
# 引入models模块
from . import models
# 引入验证码模块
from . import utils

import math
from django.shortcuts import redirect


# 验证码
def code(request):
    img, code = utils.create_code()
    # 将验证码保存到code中
    request.session['code'] = code
    file = BytesIO()
    img.save(file, 'PNG')
    return HttpResponse(file.getvalue())


# 用户登陆
def user_login(request):
    if request.method == "GET":
        return render(request, "user/login.html", {"msg": "请登录"})
    elif request.method == "POST":
        username = request.POST["username"].strip()
        password = request.POST["password"].strip()
        # 验证码
        # code = request.POST['code']
        # mycode = request.session['code']
        # if code.upper() != mycode.upper():
        #     return render(request, 'user/login.html', {'msg': '验证码输入错误'})
        # del request.session['code']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                # 将验证通过的用户信息保存到reques，
                login(request, user)
                request.session['login'] = user.id

                return render(request, "user/userInfo.html", {"user":request.user, "img": request.user.userinfo.header})
            else:
                return render(request, "user/login.html", {"error_code": 2, "msg": "你的账号已经被锁定，请联系管理员"})
        else:
            return render(request, "user/login.html", {"error_code": 3, "msg": "用户名称或者密码错误，请重新登录"})


# 用户注册
def register(request):
    if request.method == "GET":
        return render(request, "user/register.html", {"msg": "请认真填写如下选项"})
    elif request.method == "POST":
        username = request.POST["username"].strip()
        password = request.POST["password"].strip()
        nickname = request.POST["nickname"]
        confirmpwd = request.POST["confirmpwd"].strip()
        phone = request.POST["phone"]

        # 两次密码判断
        if password != confirmpwd:
            return render(request, 'user/register.html', {"error_code": 1, "msg": "两次密码不一致，请重新输入"})

        # 验证码判断
        # code = request.POST['code']
        # mycode = request.session['code']
        # if code.upper() != mycode.upper():
        #     return render(request, 'user/register.html', {'msg': '验证码输入错误'})
        # del request.session['code']

        # 判断用户名是否相可用
        if len(username) < 1:
            return render(request, "user/register.html", {"msg": "用户名不能为空！！！"})
        if len(password) < 6:
            return render(request, "user/register.html", {"msg": "密码长度不能小于6位！！！"})
        if len(phone) != 11:
            return render(request, 'user/register.html', {'msg':'手机号输入错误！！'})

        try:
            User.objects.get(username=username)
            return render(request, 'user/register.html', {"error_code": 2, "msg": "用户名已存在，请重新输入"})
        except:
            try:
                models.UserInfo.object.get(nickname=nickname)
                return render(request, "user/register.html", {"error_code": 3, "msg": "该用户昵称已经存在，请重新输入"})
            except:
                # 保存用户信息
                user = User.objects.create_user(username=username, password=password,)
                userInfo = models.UserInfo(nickname=nickname,phone=phone, user=user)

                user.save()
                userInfo.save()

                return render(request, "user/login.html", {"error_code": 1, "msg": "用户注册成功，请登录"})


# 用户退出
def user_logout(request):
    logout(request)
    return render(request, "user/login.html", {"error_code": 4, "msg": "退出成功，请重新登录"})


# 用户修改
def update(request):
    user = request.user
    if request.method == "GET":
        # user = models.User.objects.get(id=request.session['login'])
        return render(request, "user/update.html", {"user": user})
    elif request.method == 'POST':

        age = request.POST['age']
        phone = request.POST['phone']
        nickname = request.POST['nickname']
        # 获取文件域对象
        header = request.FILES.get('header')
        print(header)
        id = request.session['login']

        user.userinfo.phone = phone
        user.userinfo.age = age
        user.userinfo.nickname = nickname
        user.userinfo.header = header
        user.userinfo.save()
        return render(request, 'user/userInfo.html', {"msg": "修改成功!!", 'user': request.user,
                                                      "img": request.user.userinfo.header})


# 展示用户信息
def user_info(request):
    if request.method == "GET":
        return render(request, "user/userInfo.html", {"img": request.user.userinfo.header})
    if request.method == "POST":
        return render(request, "user/userInfo.html", {})

# 删除用户
# def delete_user(request):
# #     u_id = request.GET["id"]
# #     user = models.User.objects.get(pk=u_id)
# #     user.delete()
# #     return HttpResponse(<h2>删除成功</h2>)

# django 封装文件上传
def register2(request):
    if request.method == 'GET':
        return render(request, 'user/userInfo.html', {'msg':'请按照格式进行修改'})
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        nickname = request.POST['nickname']
        # 获取文件域对象
        header = request.FILES['header']
        print(header)
        user = models.User(username=username,
                           password=password,
                           nickname=nickname,
                           header=header)
        user.save()
        return render(request, 'user/userInfo.html',
                      {"msg": "修改成功!!", 'user': user})


# 修改密码
def update_pw(request):
    # 获取当前用户
    user = request.user
    if request.method == "GET":
        return render(request, "user/update_pw.html", {"msg": "请正确修改信息！！", "user": user})
    elif request.method == "POST":
        opassword = request.POST["opassword"].strip()
        npassword = request.POST["npassword"].strip()
        confirmpwd = request.POST["confirmpwd"]

        # 验证码判断
        # code = request.POST['code']
        # mycode = request.session['code']
        # if code.upper() != mycode.upper():
        #     return render(request, 'user/register.html', {'msg': '验证码输入错误'})
        # del request.session['code']

        user = authenticate(username=request.user.username, password=opassword)
        if user is not None:
            if npassword != confirmpwd:
                return render(request, "user/update_pw.html", {"msg": "两次输入密码不一致，请重新输入！！"})
            else:
                user.set_password(npassword)
                user.save()
                logout(request)
                return render(request, "user/login.html", {"msg": "修改成功，请重新登录..."})
        else:
            return render(request, "user/update_pw.html", {"error_code": 2, "msg": "原密码输入错误请重新输入"})

mysite/user/templates/user/login.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>会员登录</title>
		<link rel="stylesheet" type="text/css" href="/static/user/css/login.css">

	</head>
	<body>
		 <!--login -->
		<div class="top center">
			<div class="logo center">
				<a href="./index.html" target="_blank"><img src="/static/user/image/mistore_logo.png" alt=""></a>
			</div>
		</div>
		<form  method="post" action="{% url 'user:login' %}" class="form center">
			{% csrf_token %}
		<div class="login">
			<div class="login_center">
				<div class="login_top">
					<div class="left fl">会员登录</div>
					<div class="right fr">您还不是我们的会员？<a href="{% url 'user:register' %}" target="_self">立即注册</a></div>
					<div class="clear"></div>
					<div class="xian center"></div>
				</div>
                <h2>{{ msg }}</h2>
				<div class="login_main center">
					<div class="username">用户名:&nbsp;<input class="shurukuang" type="text" name="username" placeholder="请输入你的用户名"/></div>
					<div class="username">密&nbsp;&nbsp;&nbsp;&nbsp;码:&nbsp;<input class="shurukuang" type="password" name="password" placeholder="请输入你的密码"/></div>
					<div class="username">
						<div class="left fl">验证码:&nbsp;<input class="yanzhengma" type="text" name="code" placeholder="请输入验证码" autocomplete="off"/></div>
						<div class="right fl"><a href="#" onclick="changeCode()"><img id="code" src="{% url 'user:code' %} " title="点击刷新"></a></div>
						<div class="clear"></div>
					</div>
				</div>
				<div class="login_submit">
					<input class="submit" type="submit" name="submit" value="立即登录" >
				</div>

			</div>
		</div>
		<script>

			function changeCode() {
				document.getElementById("code").src = "/user/code?id="+ Math.random()
			}
    	</script>

		</form>

		<footer>
			<div class="copyright">简体 | 繁体 | English | 常见问题</div>
			<div class="copyright">小米公司版权所有-京ICP备10046444-<img src="./image/ghs.png" alt="">京公网安备11010802020134号-京ICP证110507号</div>

		</footer>

	</body>
</html>

mysite/user/templates/user/register.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>用户注册</title>
		<link rel="stylesheet" type="text/css" href="/static/user/css/login.css">
	</head>
	<body>
		<form  method="post" action="{% url 'user:register' %}">
             {% csrf_token %}
		<div class="regist">
			<div class="regist_center">
				<div class="regist_top">
					<div class="left fl">会员注册</div>
					<div class="right fr"><a href="./index.html" target="_self">小米商城</a></div>
					<div class="clear"></div>
					<div class="xian center"></div>
				</div>
                {{ msg }}
				<div class="regist_main center">
					<div class="username">用&nbsp;&nbsp;户&nbsp;&nbsp;名:&nbsp;&nbsp;<input class="shurukuang" type="text" name="username" placeholder="请输入你的用户名"/><span>请不要输入汉字</span></div>
					<div class="username">用户昵称:&nbsp;&nbsp;<input class="shurukuang" type="text" name="nickname" placeholder="请输入你的用户名"/><span>昵称为汉字</span></div>
					<div class="username">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码:&nbsp;&nbsp;<input class="shurukuang" type="password" name="password" placeholder="请输入你的密码"/><span>请输入6位以上字符</span></div>

					<div class="username">确认密码:&nbsp;&nbsp;<input class="shurukuang" type="password" name="confirmpwd" placeholder="请确认你的密码"/><span>两次密码要输入一致哦</span></div>
					<div class="username">手&nbsp;&nbsp;机&nbsp;&nbsp;号:&nbsp;&nbsp;<input class="shurukuang" type="text" name="phone" placeholder="请填写正确的手机号"/><span>填写下手机号吧，方便我们联系您！</span></div>
					<div class="username">
						<div class="left fl">验&nbsp;&nbsp;证&nbsp;&nbsp;码:&nbsp;&nbsp;<input class="yanzhengma" type="text" name="code" placeholder="请输入验证码" autocomplete="off"/></div>
						<div class="right fl"><a href="#" onclick="changeCode()"><img id="code" src="{% url 'user:code' %}" title="点击刷新"></a></div>
						<div class="clear"></div>
					</div>
				</div>
				<div class="regist_submit">
					<input class="submit" type="submit" name="submit" value="立即注册" >
				</div>
			</div>
		</div>
		<script>
			function changeCode() {
				document.getElementById("code").src = "/user/code?id="+ Math.random()
			}
    	</script>
		</form>
	</body>
</html>

mysite/user/templates/user/update.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>小米商城-个人中心</title>
		<link rel="stylesheet" type="text/css" href="/static/user/css/style.css">
	</head>
	<body>
	<!-- start header -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="./dingdanzhongxin.html">我的订单</a></div>
					<div class="fr">
						<ul>
							{% if request.user.is_active %}
								<li><a href="./login.html" target="_blank">欢迎{{user}}登录系统</a></li>
								<li>|</li>
								<li><a href="{% url 'user:user_logout'%}" target="_blank" >退出</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
							{% else %}
								<li><a href="{% url 'user:login'%}" target="_blank" >登录</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
							{% endif %}
							<!--<li><a href="./login.html" target="_blank">登录</a></li>-->
							<!--<li>|</li>-->
							<!--<li><a href="./register.html" target="_blank" >注册</a></li>-->
							<!--<li>|</li>-->
							<!--<li><a href="#top">个人中心</a></li>-->
						</ul>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->
	<!-- start banner_x -->
		<div class="banner_x center">
			<a href="./index.html" target="_blank"><div class="logo fl"></div></a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="">小米手机</a></li>
					<li><a href="">红米</a></li>
					<li><a href="">平板·笔记本</a></li>
					<li><a href="">电视</a></li>
					<li><a href="">盒子·影音</a></li>
					<li><a href="">路由器</a></li>
					<li><a href="">智能硬件</a></li>
					<li><a href="">服务</a></li>
					<li><a href="">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->
<!-- self_info -->
	<div class="grzxbj">
		<div class="selfinfo center">
		<div class="lfnav fl">
			<div class="ddzx">订单中心</div>
			<div class="subddzx">
				<ul>
					<li><a href="./dingdanzhongxin.html" >我的订单</a></li>
					<li><a href="">意外保</a></li>
					<li><a href="">团购订单</a></li>
					<li><a href="">评价晒单</a></li>
				</ul>
			</div>
			<div class="ddzx">个人中心</div>
			<div class="subddzx">
				<ul>
					<li><a href="./self_info.html" style="color:#ff6700;font-weight:bold;">我的个人中心</a></li>
					<li><a href="">修改密码</a></li>
					<li><a href="">优惠券</a></li>
					<li><a href="">收货地址</a></li>
				</ul>
			</div>
		</div>
		<div class="rtcont fr">
			<div class="grzlbt ml40">我的资料</div>
			<form action="/user/update/" method="post" enctype="multipart/form-data">
			{{ msg }}
			{% csrf_token %}
			<div class="subgrzl ml40" id="biankuang">
				<span>昵称</span>
				<input  style="font-size: 20px" type="text" value="{{user.userinfo.nickname}}" name="nickname" autocomplete="off">
			</div>
			<div class="subgrzl ml40">
				<span>手机号</span>
				<input style="font-size: 20px" type="text" value="{{user.userinfo.phone}}" name="phone" autocomplete="off">
			</div>
			<div class="subgrzl ml40">
				<span>年龄</span>
				<input style="font-size: 20px" type="text" value="{{user.userinfo.age}}" name="age"  autocomplete="off">
			</div>
			<div class="subgrzl ml40">
				<span>头像</span>
				<input style="font-size: 17px" type="file" value="{{user.userinfo.header}}" name="header" autocomplete="off" >
			</div>
			<!--<div class="subgrzl ml40">-->
				<!--<span>收货地址</span>-->
				<!--<input style="font-size: 17px" type="text" value="{{user.userinfo.site}}" name="site" autocomplete="off">-->
			<!--</div>-->
			<button id="xiu" type="submit">确认修改</button>
			</form>
		</div>
		<div class="clear"></div>
		</div>
	</div>
<!-- self_info -->

		<footer class="mt20 center">
			<div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
			<div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div>
			<div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>
		</footer>
	</body>
</html>

mysite/user/templates/user/update_pw.html
{% extends 'base.html'%}


{% block pwd %}
    <div class="grzlbt ml40">修改密码</div>
<form action="{% url 'user:update_pw'%}" method="post">
    <div class="h1">
        {{ msg }}
        {% csrf_token %}

        <div class="username h2">旧&nbsp;&nbsp;密&nbsp;&nbsp;码:&nbsp;&nbsp;
            <input class="shurukuang h3" type="password" name="opassword" placeholder="请输入您的旧密码"/>
            <span>请输入6位以上字符</span>
        </div>
        <div class="username h2">新&nbsp;&nbsp;密&nbsp;&nbsp;码:&nbsp;&nbsp;
            <input class="shurukuang h3" type="password" name="npassword" placeholder="请输入您的新密码"/>
            <span>请输入6位以上字符</span>
        </div>

        <div class="username h2">确认密码:&nbsp;&nbsp;
            <input class="shurukuang h3" type="password" name="confirmpwd" placeholder="请确认您的新密码"/>
            <span>两次密码要输入一致哦</span>
        </div>
        <div class="username ">
            <div class="username h2">验&nbsp;&nbsp;证&nbsp;&nbsp;码:&nbsp;&nbsp;
                <input class="yanzhengma h3" type="text" name="code" placeholder="请输入验证码" autocomplete="off"/>
            </div>
            <div class="right h5">
                <a href="#" onclick="changeCode()">
                    <img id="code" src="{% url 'user:code' %} " title="点击刷新">
                </a>
            </div>
            <div class="clear"></div>
        </div>
        <input class="submit h4" type="submit" name="submit" value="修改密码" >
    </div>

    </form>
{% endblock %}

mysite/user/templates/user/userInfo.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <!--<meta name="author" content="order by dede58.com"/>-->
		<title>小米商城-个人中心</title>
		<link rel="stylesheet" type="text/css" href="/static/user/css/style.css">
	</head>
	<body>
	<!-- start header -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="./dingdanzhongxin.html">我的订单</a></div>
					<div class="fr">
						<ul>
							{% if request.user.is_active %}
								<li><a href="./login.html" target="_blank">欢迎{{ user }}登录系统</a></li>
								<li>|</li>
								<li><a href="{% url 'user:user_logout'%}" target="_blank" >退出</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
							{% else %}
								<li><a href="{% url 'user:login'%}" target="_blank" >登录</a></li>
								<li><a href="{% url 'user:register'%}" target="_blank" >注册</a></li>
							{% endif %}
								<!--<li>|</li>-->
								<!--<li><a href="#top">个人中心</a></li>-->
								<!--<li>{{user}}</li>-->
						</ul>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->
	<!-- start banner_x -->
		<div class="banner_x center">
			<a href="/" target="_blank"><div class="logo fl"></div></a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="">小米手机</a></li>
					<li><a href="">红米</a></li>
					<li><a href="">平板·笔记本</a></li>
					<li><a href="">电视</a></li>
					<li><a href="">盒子·影音</a></li>
					<li><a href="">路由器</a></li>
					<li><a href="">智能硬件</a></li>
					<li><a href="">服务</a></li>
					<li><a href="">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="get">
					{% csrf_token %}
					<div class="text fl">
						<input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->
<!-- self_info -->
	<div class="grzxbj">
		<div class="selfinfo center">
		<div class="lfnav fl">
			<div class="ddzx">订单中心</div>
			<div class="subddzx">
				<ul>
					<li><a href="./dingdanzhongxin.html" >我的订单</a></li>
					<li><a href="">意外保</a></li>
					<li><a href="">团购订单</a></li>
					<li><a href="">评价晒单</a></li>
				</ul>
			</div>
			<div class="ddzx">个人中心</div>
			<div class="subddzx">
				<ul>
					<li><a href="./self_info.html" style="color:#ff6700;font-weight:bold;">我的个人中心</a></li>
					<li><a href="{% url 'user:update_pw' %}">修改密码</a></li>
					<li><a href="">优惠券</a></li>
					<li><a href="">收货地址</a></li>
				</ul>
			</div>
		</div>
		<div class="rtcont fr">
			<div class="grzlbt ml40">我的资料</div>
			<form action="/user/user_info/">
				{% csrf_token %}

			<div class="aa ml40">
				<span>用户头像</span>
				<img style="height: 100px;width: 100px; border-radius: 50%" src="/static/upload/{{ img }}" alt="">
			</div>
			<div class="subgrzl ml40">
				<span>昵称</span>
				<span>{{user.userinfo.nickname}}</span>
				<span><a href="/user/update/">编辑</a></span>
			</div>
			<div class="subgrzl ml40">
				<span>手机号</span>
				<span>{{user.userinfo.phone}}</span>
				<span><a href="/user/update/">编辑</a></span>
			</div>

			<div class="subgrzl ml40">
				<span>密码</span>
				<span>************</span>
				<span><a href="/user/update/">编辑</a></span>
			</div>
			<div class="subgrzl ml40">
				<span>年龄</span>
				<span>{{user.userinfo.age}}</span>
				<span><a href="/user/update/">编辑</a></span></div>
			</form>
		</div>
		<div class="clear"></div>
		</div>
	</div>
<!-- self_info -->

		<footer class="mt20 center">
			<div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
			<div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div>
			<div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>
		</footer>
	</body>
</html>